version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - "8080:8000"
    image: app:django
    container_name: E_Commerce
    command: python manage.py runserver 0.0.0.0:8000
